WAREHOUSE_CHOICES = (
    ('Active', 'Active'),
    ('Inactive', 'Inactive'),
    ('Closed', 'Closed'),
)

WAREHOUSE_SIZES = (
    ('Small', 'Small'),
    ('Medium', 'Medium'),
    ('Large', 'Large'),
)

WAREHOUSE_CAPACITY = (
    ('Low', 'Low'),
    ('Medium', 'Medium'),
    ('High', 'High'),
)

WAREHOUSE_TYPE = (
    ('Owned', 'Owned'),
    ('Leased', 'Leased'),
    ('Rental', 'Rental'),
)

INVENTORY_STATUS = (
    ('Available', 'Available'),
    ('Low', 'Low'),
    ('Out of Stock', 'Out of Stock'),
    ('Discontinued', 'Discontinued'),
    ('Damaged', 'Damaged'),
    ('Lost', 'Lost'),
    ('Expired', 'Expired'),
)

DISCOUNT_TYPE = (
    ('Percentage', 'Percentage'),
    ('Amount', 'Amount'),
)

INWARD_TYPE = (
    ('Purchased', 'Purchased'),
    ('Transferred', 'Transferred'),
    ('Returned', 'Returned'),
    ('Replacement', 'Replacement'),
)

INVENTORY_LOG_STATUS = (
    ('Inwarded', 'Inwarded'),
    ('Outwarded', 'Outwarded'),
    ('Damaged', 'Damaged'),
    ('Lost', 'Lost'),
    ('Returned', 'Returned'),
    ('Discontinued', 'Discontinued'),
    ('Expired', 'Expired'),
    ('Adjustment', 'Adjustment'),
    ('Warehouse Transfer', 'Warehouse Transfer'),
)

PAYMENT_ORDER_METHODS = (
    ('Cash', 'Cash'),
    ('Cheque', 'Cheque'),
    ('Online', 'Online'),
    ('Paypal', 'Paypal'),
)

PAYMENT_STATUS = (
    ('Unpaid', 'Unpaid'),
    ('Partially Paid', 'Partially Paid'),
    ('Fully Paid', 'Fully Paid'),
    ('Cancelled', 'Cancelled'),
)

PURCHASE_ORDER_STATUS = (
    ('Pending', 'Pending'),
    ('Shipped', 'Shipped'),
    ('Delivered', 'Delivered'),
    ('Returned', 'Returned'),
)

SHIPPING_TYPE = (
    ('Free', 'Free'),
    ('Standard', 'Standard'),
    ('Express', 'Express'),
    ('Priority', 'Priority'),
)

STATUS = (
    ('Draft', 'Draft'),
    ('Pending', 'Pending'),
    ('Purchased', 'Purchased'),
    ('Returned', 'Returned'),
)

PRODUCT_AVAILABILITY = (
    ('Available', 'Available'),
    ('Out of Stock', 'Out of Stock'),
    ('Coming Soon', 'Coming Soon'),
)

PRODUCT_QUESTION_STATUS = (
    ('Active', 'Active'),
    ('Inactive', 'Inactive'),
)

PRODUCT_REVIEWS_STATUS = (
    ('Active', 'Active'),
    ('Inactive', 'Inactive'),
)

ADDRESS_TYPES = (
    ('HOME', 'Home'),
    ('Office', 'Office'),
    ('OTHER', 'Other'),
)

ACCOUNT_CHOICES = (
    ('Active', 'Active'),
    ('Inactive', 'Inactive'),
    ('Banned', 'Banned'),
)
ROLES = (
    ('Admin', 'Admin'),
    ('User', 'User'),
    ('Supplier', 'Supplier'),
    ('Customer', 'Customer'),
    ('Staff', 'Staff'),
    ('Manager', 'Manager'),
)
LANGAUGES = (
    ('English', 'English'),
    ('French', 'French'),
    ('Spanish', 'Spanish'),
    ('German', 'German'),
    ('Italian', 'Italian'),
    ('Chinese', 'Chinese'),
    ('Japanese', 'Japanese'),
    ('Korean', 'Korean'),
    ('Krio', 'Krio'),
    ('Russian', 'Russian'),
    ('Portuguese', 'Portuguese'),
    ('Arabic', 'Arabic'),
    ('Thai', 'Thai'),
    ('Vietnamese', 'Vietnamese'),
    ('Turkish', 'Turkish'),
    ('Indonesian', 'Indonesian'),
    ('Malay', 'Malay'),
    ('Dutch', 'Dutch'),
    ('Polish', 'Polish'),
    ('Greek', 'Greek'),
    ('Czech', 'Czech'),
    ('Danish', 'Danish'),
    ('Swedish', 'Swedish'),
)
DEPARTMENTS = (
    ('Marketing & Sales', 'Marketing & Sales'),
    ('Finance & Admin', 'Finance & Admin'),
    ('Operations', 'Operations'),
    ('Customer Service & Support', 'Customer Service & Support'),
    ('HR', 'HR'),
    ('IT', 'IT'),
    ('Admin', 'Admin'),
    ('Production', 'Production'),
    ('Quality Control', 'Quality Control'),
    ('Purchase', 'Purchase'),
    ('Logistics', 'Logistics'),
    ('Customer Service', 'Customer Service'),
    ('R & D', 'R & D'),
    ('Legal', 'Legal'),
    ('Security', 'Security'),
    ('Housekeeping', 'Housekeeping'),
    ('Engineering', 'Engineering'),
    ('Design', 'Design'),
    ('Testing', 'Testing'),
    ('Training', 'Training'),
)
DESIGNATION = (
    ('CEO', 'CEO'),
    ('CIO', 'CIO'),
    ('CMS', 'CMS'),
    ('CSO', 'CSO'),
)
TIME_ZONES = (
    ('UTC-12:00', 'UTC-12:00'),
    ('UTC-11:00', 'UTC-11:00'),
    ('UTC-10:00', 'UTC-10:00'),
    ('UTC-09:30', 'UTC-09:30'),
    ('UTC-09:00', 'UTC-09:00'),
    ('UTC-08:00', 'UTC-08:00'),
    ('UTC-07:00', 'UTC-07:00'),
    ('UTC-06:00', 'UTC-06:00'),
    ('UTC-05:00', 'UTC-05:00'),
    ('UTC-04:00', 'UTC-04:00'),
    ('UTC-03:30', 'UTC-03:30'),
    ('UTC-03:00', 'UTC-03:00'),
    ('UTC-02:00', 'UTC-02:00'),
    ('UTC-01:00', 'UTC-01:00'),
    ('UTC+00:00', 'UTC+00:00'),
    ('UTC+01:00', 'UTC+01:00'),
    ('UTC+02:00', 'UTC+02:00'),
    ('UTC+03:00', 'UTC+03:00'),
    ('UTC+03:30', 'UTC+03:30'),
    ('UTC+04:00', 'UTC+04:00'),
    ('UTC+04:30', 'UTC+04:30'),
    ('UTC+05:00', 'UTC+05:00'),
    ('UTC+05:30', 'UTC+05:30'),
    ('UTC+05:45', 'UTC+05:45'),
    ('UTC+06:00', 'UTC+06:00'),
    ('UTC+06:30', 'UTC+06:30'),
    ('UTC+07:00', 'UTC+07:00'),
    ('UTC+08:00', 'UTC+08:00'),
    ('UTC+08:45', 'UTC+08:45'),
    ('UTC+09:00', 'UTC+09:00'),
    ('UTC+09:30', 'UTC+09:30'),
    ('UTC+10:00', 'UTC+10:00'),
    ('UTC+10:30', 'UTC+10:30'),
    ('UTC+11:00', 'UTC+11:00'),
    ('UTC+12:00', 'UTC+12:00'),
    ('UTC+12:45', 'UTC+12:45'),
    ('UTC+13:00', 'UTC+13:00'),
    ('UTC+14:00', 'UTC+14:00')
)
CURRENCIES = (
    ('AED', 'AED'),
    ('AFN', 'AFN'),
    ('ALL', 'ALL'),
    ('AMD', 'AMD'),
    ('ANG', 'ANG'),
    ('AOA', 'AOA'),
    ('ARS', 'ARS'),
    ('AUD', 'AUD'),
    ('AWG', 'AWG'),
    ('AZN', 'AZN'),
    ('BAM', 'BAM'),
    ('BBD', 'BBD'),
    ('BDT', 'BDT'),
    ('BGN', 'BGN'),
    ('BHD', 'BHD'),
    ('BIF', 'BIF'),
    ('BMD', 'BMD'),
    ('BND', 'BND'),
    ('BOB', 'BOB'),
    ('BRL', 'BRL'),
    ('BSD', 'BSD'),
    ('BTN', 'BTN'),
    ('BWP', 'BWP'),
    ('BYN', 'BYN'),
    ('BZD', 'BZD'),
    ('CAD', 'CAD'),
    ('CDF', 'CDF'),
    ('CHF', 'CHF'),
    ('CLP', 'CLP'),
    ('CNY', 'CNY'),
    ('COP', 'COP'),
    ('CRC', 'CRC'),
    ('CUP', 'CUP'),
    ('CVE', 'CVE'),
    ('CZK', 'CZK'),
    ('DJF', 'DJF'),
    ('DKK', 'DKK'),
    ('DOP', 'DOP'),
    ('DZD', 'DZD'),
    ('EGP', 'EGP'),
    ('ERN', 'ERN'),
    ('ETB', 'ETB'),
    ('EUR', 'EUR'),
    ('FJD', 'FJD'),
    ('FKP', 'FKP'),
    ('FOK', 'FOK'),
    ('GBP', 'GBP'),
    ('GEL', 'GEL'),
    ('GGP', 'GGP'),
    ('GHS', 'GHS'),
    ('GIP', 'GIP'),
    ('GMD', 'GMD'),
    ('GNF', 'GNF'),
    ('GTQ', 'GTQ'),
    ('GYD', 'GYD'),
    ('HKD', 'HKD'),
    ('HNL', 'HNL'),
    ('HRK', 'HRK'),
    ('HTG', 'HTG'),
    ('HUF', 'HUF'),
    ('IDR', 'IDR'),
    ('ILS', 'ILS'),
    ('IMP', 'IMP'),
    ('INR', 'INR'),
    ('IQD', 'IQD'),
    ('IRR', 'IRR'),
    ('ISK', 'ISK'),
    ('JEP', 'JEP'),
    ('JMD', 'JMD'),
    ('JOD', 'JOD'),
    ('JPY', 'JPY'),
    ('KES', 'KES'),
    ('KGS', 'KGS'),
    ('KHR', 'KHR'),
    ('KID', 'KID'),
    ('KMF', 'KMF'),
    ('KRW', 'KRW'),
    ('KWD', 'KWD'),
    ('KYD', 'KYD'),
    ('KZT', 'KZT'),
    ('LAK', 'LAK'),
    ('LBP', 'LBP'),
    ('LKR', 'LKR'),
    ('LRD', 'LRD'),
    ('LSL', 'LSL'),
    ('LYD', 'LYD'),
    ('MAD', 'MAD'),
    ('MDL', 'MDL'),
    ('MGA', 'MGA'),
    ('MKD', 'MKD'),
    ('MMK', 'MMK'),
    ('MNT', 'MNT'),
    ('MOP', 'MOP'),
    ('MRU', 'MRU'),
    ('MUR', 'MUR'),
    ('MVR', 'MVR'),
    ('MWK', 'MWK'),
    ('MXN', 'MXN'),
    ('MYR', 'MYR'),
    ('MZN', 'MZN'),
    ('NAD', 'NAD'),
    ('NGN', 'NGN'),
    ('NIO', 'NIO'),
    ('NOK', 'NOK'),
    ('NPR', 'NPR'),
    ('NZD', 'NZD'),
    ('OMR', 'OMR'),
    ('PAB', 'PAB'),
    ('PEN', 'PEN'),
    ('PGK', 'PGK'),
    ('PHP', 'PHP'),
    ('PKR', 'PKR'),
    ('PLN', 'PLN'),
    ('PYG', 'PYG'),
    ('QAR', 'QAR'),
    ('RON', 'RON'),
    ('RSD', 'RSD'),
    ('RUB', 'RUB'),
    ('RWF', 'RWF'),
    ('SAR', 'SAR'),
    ('SBD', 'SBD'),
    ('SCR', 'SCR'),
    ('SDG', 'SDG'),
    ('SEK', 'SEK'),
    ('SGD', 'SGD'),
    ('SHP', 'SHP'),
    ('SLL', 'SLL'),
    ('SOS', 'SOS'),
    ('SRD', 'SRD'),
    ('SSP', 'SSP'),
    ('STN', 'STN'),
    ('SYP', 'SYP'),
    ('SZL', 'SZL'),
    ('THB', 'THB'),
    ('TJS', 'TJS'),
    ('TMT', 'TMT'),
    ('TND', 'TND'),
    ('TOP', 'TOP'),
    ('TRY', 'TRY'),
    ('TTD', 'TTD'),
    ('TVD', 'TVD'),
    ('TWD', 'TWD'),
    ('TZS', 'TZS'),
    ('UAH', 'UAH'),
    ('UGX', 'UGX'),
    ('USD', 'USD'),
    ('UYU', 'UYU'),
    ('UZS', 'UZS'),
    ('VES', 'VES'),
    ('VND', 'VND'),
    ('VUV', 'VUV'),
    ('WST', 'WST'),
    ('XAF', 'XAF'),
    ('XCD', 'XCD'),
    ('XDR', 'XDR'),
    ('XOF', 'XOF'),
    ('XPF', 'XPF'),
    ('YER', 'YER'),
    ('ZAR', 'ZAR'),
    ('ZMW', 'ZMW'),
    ('ZWL', 'ZWL'),
)

PLAN_TYPES = (
    ('Basic', 'Basic'),
    ('Premium', 'Premium'),
    ('Premium Plus', 'Premium Plus'),
    ('Enterprise', 'Enterprise'),
)
